version: "2"
services:
  app:
    build: ./app
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    networks:
      - backend
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  nginx:
    build: ./nginx
    depends_on:
      - app
    networks:
      - backend
    ports:
      - "80:80"
networks:
  backend:
